### ISSUE TITLE
Articles Routes

### ISSUE THREAD

**Issue by JackyChiu** [JackyChiu/realworld-starter-kit#5]
- [ ] Feed
- [x] All Articles
- [x] Articles by Author
- [x] Articles by Favourited by username
- [x] Articles by tag
- [x] Create Article 
- [x] Single Article
- [x] Delete Article
- [x] Update Article
- [x] Favourite Article
- [x] Unfavourite Article

**Comment by JackyChiu** [comment]
From #17:

## TODO:

### Articles filtering
- [ ] Chained query filtering like **?tag=tag1&author=jake&favorited=josh**

### Create/Update Article
- [ ] Handle duplication article, make the slug unique

### Favourite / Unfavourite Article
- [ ] Update favorites count on article
